title: Berik's blog
email: berik@visschers.nu
description: >-
  A log of repairs and creations
domain: visschers.nu
url: "https://visschers.nu"
baseurl: ""

github_username:  berikv

theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
minima:
  skin: dark